language: python
sudo: required
dist: bionic

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    packages:
      - jq

before_install:
  - pip install --quiet --upgrade pip codecov

install:
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false
